name: Submit a new snippet
description: Submit a new snippet to the repository
labels: ["new snippet"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a new snippet to the repository! Please fill out the form below, and we'll get back to you as soon as possible.
  - type: input
    id: snippet-id
    attributes:
      label: Snippet ID
      description: The ID of the snippet (must be unique and only contain lowercase letters, numbers, and dashes)
      placeholder: "my-awesome-snippet"
    validations:
      required: true
  - type: input
    id: snippet-name
    attributes:
      label: Snippet name
      description: The name of the snippet
      placeholder: "My awesome snippet"
    validations:
      required: true
  - type: textarea
    id: snippet-description
    attributes:
      label: Snippet description
      description: A short description of the snippet
      placeholder: "This snippet does something awesome"
    validations:
      required: true
  - type: textarea
    id: snippet-code
    attributes:
      label: Snippet code
      description: The code for the snippet
      placeholder: |
        ```js
        console.log("Hello world!");
        ```
    validations:
      required: true
  # - type: textarea
  #   id: snippet-usage
  #   attributes:
  #     label: Snippet usage
  #     description: How to use the snippet
  #     placeholder: |
  #       ```js
  #       // How to use the snippet
  #       ```
  #   validations:
  #     required: true
  - type: dropdown
    id: snippet-language
    attributes:
      label: Snippet language
      description: The language of the snippet
      options:
        - 1C Enterprise
        - 2-Dimensional Array
        - 4D
        - ABAP
        - ABAP CDS
        - ActionScript
        - Ada
        - Adblock Filter List
        - Adobe Font Metrics
        - Agda
        - AGS Script
        - AIDL
        - AL
        - Alloy
        - Alpine Abuild
        - Altium Designer
        - AMPL
        - AngelScript
        - Ant Build System
        - Antlers
        - ANTLR
        - ApacheConf
        - Apex
        - API Blueprint
        - APL
        - Apollo Guidance Computer
        - AppleScript
        - Arc
        - AsciiDoc
        - ASL
        - ASP.NET
        - AspectJ
        - Assembly
        - Astro
        - Asymptote
        - ATS
        - Augeas
        - AutoHotkey
        - AutoIt
        - Avro IDL
        - Awk
        - Ballerina
        - BASIC
        - Batchfile
        - Beef
        - Befunge
        - Berry
        - BibTeX
        - Bicep
        - Bikeshed
        - Bison
        - BitBake
        - Blade
        - BlitzBasic
        - BlitzMax
        - Bluespec
        - Boo
        - Boogie
        - Brainfuck
        - BrighterScript
        - Brightscript
        - Browserslist
        - C
        - C#
        - C++
        - C2hs Haskell
        - Cabal Config
        - Cadence
        - Cairo
        - CameLIGO
        - CAP CDS
        - Cap&#39;n Proto
        - CartoCSS
        - Ceylon
        - Chapel
        - Charity
        - ChucK
        - Circom
        - Cirru
        - Clarion
        - Clarity
        - Classic ASP
        - Clean
        - Click
        - CLIPS
        - Clojure
        - Closure Templates
        - Cloud Firestore Security Rules
        - CMake
        - COBOL
        - CodeQL
        - CoffeeScript
        - ColdFusion
        - ColdFusion CFC
        - COLLADA
        - Common Lisp
        - Common Workflow Language
        - Component Pascal
        - Cool
        - Coq
        - Crystal
        - CSON
        - Csound
        - Csound Document
        - Csound Score
        - CSS
        - CSV
        - Cuda
        - CUE
        - Curry
        - CWeb
        - Cycript
        - Cypher
        - Cython
        - D
        - D2
        - Dafny
        - Darcs Patch
        - Dart
        - DataWeave
        - Debian Package Control File
        - DenizenScript
        - Dhall
        - DIGITAL Command Language
        - DirectX 3D File
        - DM
        - Dockerfile
        - Dogescript
        - Dotenv
        - DTrace
        - Dylan
        - E
        - Earthly
        - Easybuild
        - eC
        - Ecere Projects
        - ECL
        - ECLiPSe
        - Ecmarkup
        - EditorConfig
        - Eiffel
        - EJS
        - Elixir
        - Elm
        - Elvish
        - Elvish Transcript
        - Emacs Lisp
        - EmberScript
        - EQ
        - Erlang
        - Euphoria
        - F#
        - F*
        - Factor
        - Fancy
        - Fantom
        - Faust
        - Fennel
        - FIGlet Font
        - Filebench WML
        - Filterscript
        - fish
        - Fluent
        - FLUX
        - Forth
        - Fortran
        - Fortran Free Form
        - FreeBasic
        - FreeMarker
        - Frege
        - Futhark
        - G-code
        - Game Maker Language
        - GAML
        - GAMS
        - GAP
        - GCC Machine Description
        - GDB
        - GDScript
        - GEDCOM
        - Gemfile.lock
        - Gemini
        - Genero
        - Genero Forms
        - Genie
        - Genshi
        - Gentoo Ebuild
        - Gentoo Eclass
        - Gerber Image
        - Gherkin
        - Git Attributes
        - Git Config
        - Git Revision List
        - Gleam
        - GLSL
        - Glyph
        - Gnuplot
        - Go
        - Go Checksums
        - Go Module
        - Go Workspace
        - Godot Resource
        - Golo
        - Gosu
        - Grace
        - Gradle
        - Grammatical Framework
        - GraphQL
        - Graphviz (DOT)
        - Groovy
        - Groovy Server Pages
        - GSC
        - Hack
        - Haml
        - Handlebars
        - HAProxy
        - Harbour
        - Haskell
        - Haxe
        - HCL
        - HiveQL
        - HLSL
        - HOCON
        - HolyC
        - hoon
        - Hosts File
        - HTML
        - HTML+ECR
        - HTML+EEX
        - HTML+ERB
        - HTML+PHP
        - HTML+Razor
        - HTTP
        - HXML
        - Hy
        - HyPhy
        - IDL
        - Idris
        - Ignore List
        - IGOR Pro
        - ImageJ Macro
        - Imba
        - Inform 7
        - INI
        - Ink
        - Inno Setup
        - Io
        - Ioke
        - Isabelle
        - Isabelle ROOT
        - J
        - Janet
        - JAR Manifest
        - Jasmin
        - Java
        - Java Properties
        - Java Server Pages
        - JavaScript
        - JavaScript+ERB
        - JCL
        - Jest Snapshot
        - JetBrains MPS
        - JFlex
        - Jinja
        - Jison
        - Jison Lex
        - Jolie
        - jq
        - JSON
        - JSON with Comments
        - JSON5
        - JSONiq
        - JSONLD
        - Jsonnet
        - Julia
        - Jupyter Notebook
        - Just
        - Kaitai Struct
        - KakouneScript
        - KerboScript
        - KiCad Layout
        - KiCad Legacy Layout
        - KiCad Schematic
        - Kotlin
        - KRL
        - kvlang
        - LabVIEW
        - Lark
        - Lasso
        - Latte
        - Lean
        - Less
        - Lex
        - LFE
        - LigoLANG
        - LilyPond
        - Limbo
        - Liquid
        - Literate Agda
        - Literate CoffeeScript
        - Literate Haskell
        - LiveScript
        - LLVM
        - Logos
        - Logtalk
        - LOLCODE
        - LookML
        - LoomScript
        - LSL
        - Lua
        - M
        - M4
        - M4Sugar
        - Macaulay2
        - Makefile
        - Mako
        - Markdown
        - Marko
        - Mask
        - Mathematica
        - MATLAB
        - Max
        - MAXScript
        - mcfunction
        - MDX
        - Mercury
        - Mermaid
        - Meson
        - Metal
        - MiniD
        - MiniYAML
        - Mint
        - Mirah
        - mIRC Script
        - MLIR
        - Modelica
        - Modula-2
        - Modula-3
        - Module Management System
        - Monkey
        - Monkey C
        - Moocode
        - MoonScript
        - Motoko
        - Motorola 68K Assembly
        - Move
        - MQL4
        - MQL5
        - MTML
        - MUF
        - mupad
        - Mustache
        - Myghty
        - nanorc
        - Nasal
        - NASL
        - NCL
        - Nearley
        - Nemerle
        - nesC
        - NetLinx
        - NetLinx+ERB
        - NetLogo
        - NewLisp
        - Nextflow
        - Nginx
        - Nim
        - Nit
        - Nix
        - NPM Config
        - NSIS
        - Nu
        - NumPy
        - Nunjucks
        - Nushell
        - NWScript
        - OASv2-json
        - OASv2-yaml
        - OASv3-json
        - OASv3-yaml
        - Objective-C
        - Objective-C++
        - Objective-J
        - ObjectScript
        - OCaml
        - Odin
        - Omgrofl
        - ooc
        - Opa
        - Opal
        - Open Policy Agent
        - OpenAPI Specification v2
        - OpenAPI Specification v3
        - OpenCL
        - OpenEdge ABL
        - OpenQASM
        - OpenRC runscript
        - OpenSCAD
        - Option List
        - Org
        - Ox
        - Oxygene
        - Oz
        - P4
        - Pact
        - Pan
        - Papyrus
        - Parrot
        - Parrot Assembly
        - Parrot Internal Representation
        - Pascal
        - Pawn
        - PDDL
        - PEG.js
        - Pep8
        - Perl
        - PHP
        - PicoLisp
        - PigLatin
        - Pike
        - PlantUML
        - PLpgSQL
        - PLSQL
        - PogoScript
        - Polar
        - Pony
        - Portugol
        - PostCSS
        - PostScript
        - POV-Ray SDL
        - PowerBuilder
        - PowerShell
        - Prisma
        - Processing
        - Procfile
        - Prolog
        - Promela
        - Propeller Spin
        - Pug
        - Puppet
        - PureBasic
        - PureScript
        - Pyret
        - Python
        - Python console
        - Python traceback
        - q
        - Q#
        - QMake
        - QML
        - Qt Script
        - Quake
        - R
        - Racket
        - Ragel
        - Raku
        - RAML
        - Rascal
        - RBS
        - RDoc
        - REALbasic
        - Reason
        - ReasonLIGO
        - Rebol
        - Record Jar
        - Red
        - Redcode
        - Regular Expression
        - Ren&#39;Py
        - RenderScript
        - ReScript
        - reStructuredText
        - REXX
        - Ring
        - Riot
        - RMarkdown
        - RobotFramework
        - Roff
        - Roff Manpage
        - Rouge
        - RouterOS Script
        - RPC
        - RPGLE
        - Ruby
        - RUNOFF
        - Rust
        - Sage
        - SaltStack
        - SAS
        - Sass
        - Scala
        - Scaml
        - Scenic
        - Scheme
        - Scilab
        - SCSS
        - sed
        - Self
        - ShaderLab
        - Shell
        - ShellCheck Config
        - ShellSession
        - Shen
        - Sieve
        - Simple File Verification
        - Singularity
        - Slash
        - Slice
        - Slim
        - Smali
        - Smalltalk
        - Smarty
        - Smithy
        - SmPL
        - SMT
        - Snakemake
        - Solidity
        - SourcePawn
        - SPARQL
        - SQF
        - SQL
        - SQLPL
        - Squirrel
        - SRecode Template
        - Stan
        - Standard ML
        - Starlark
        - Stata
        - STL
        - StringTemplate
        - Stylus
        - SubRip Text
        - SugarSS
        - SuperCollider
        - Svelte
        - SVG
        - Sway
        - Swift
        - SWIG
        - SystemVerilog
        - Talon
        - Tcl
        - Tcsh
        - Terra
        - TeX
        - Textile
        - TextMate Properties
        - Thrift
        - TI Program
        - TL-Verilog
        - TLA
        - TOML
        - TSQL
        - TSV
        - TSX
        - Turing
        - Twig
        - TXL
        - TypeScript
        - Unified Parallel C
        - Unity3D Asset
        - Unix Assembly
        - Uno
        - UnrealScript
        - UrWeb
        - V
        - Vala
        - Valve Data Format
        - VBA
        - VBScript
        - VCL
        - Velocity Template Language
        - Verilog
        - VHDL
        - Vim Help File
        - Vim Script
        - Vim Snippet
        - Visual Basic .NET
        - Visual Basic 6.0
        - Volt
        - Vue
        - Vyper
        - WDL
        - Web Ontology Language
        - WebAssembly
        - WebAssembly Interface Type
        - WebIDL
        - WGSL
        - Whiley
        - Wikitext
        - Windows Registry Entries
        - wisp
        - Witcher Script
        - Wollok
        - World of Warcraft Addon Data
        - Wren
        - X10
        - xBase
        - XC
        - XML
        - XML Property List
        - Xojo
        - Xonsh
        - XProc
        - XQuery
        - XS
        - XSLT
        - Xtend
        - Yacc
        - YAML
        - YARA
        - YASnippet
        - Yul
        - ZAP
        - Zeek
        - ZenScript
        - Zephir
        - Zig
        - ZIL
        - Zimpl
    validations:
      required: true
